Repository panjips/eventmakers, pull requests merged in 2024-02, with the labels that each got.

#9 feat: add register func
  src/app/(auth)/register/page.js
  src/app/dashboard/page.js
  src/components/auth/components/register.jsx
  src/components/auth/hooks/useRegister.jsx
Labels: enhancement

#13 12 create dashboard func
  src/app/dashboard/layout.js
  src/app/dashboard/page.js
  src/components/auth/components/login.jsx
  src/components/auth/hooks/useLogin.jsx
  src/components/dashboard/components/card.jsx
  src/components/dashboard/components/dashboard.jsx
  src/components/dashboard/hooks/useRegisteredEvent.jsx
Labels: enhancement

#17 16 create manage func
  package-lock.json
  package.json
  src/app/dashboard/manage/page.js
  src/components/dashboard/components/dashboard.jsx
  src/components/dashboard/components/sidebar.jsx
  src/components/dashboard/hooks/useRegisteredEvent.jsx
  src/components/manage-event/atoms/itemTable.jsx
  src/components/manage-event/components/eventForm.jsx
  src/components/manage-event/components/eventTable.jsx
  src/components/manage-event/components/manageEvent.jsx
  src/components/manage-event/hooks/useCreateEvent.jsx
  src/components/manage-event/hooks/useDeleteEvent.jsx
  src/components/manage-event/hooks/useEditEvent.jsx
  src/components/manage-event/hooks/useGetCreatedEvent.jsx
  src/components/manage-event/providers.jsx
  src/middleware.js
Labels: enhancement

#19 style: complete landing page UI
  public/wave1.svg
  public/wave2.svg
  src/app/(home)/layout.js
  src/app/(home)/page.js
  src/app/dashboard/layout.js
  src/app/layout.js
  src/app/page.js
  src/components/landing/components/banner.jsx
  src/components/landing/components/cardEvent.jsx
  src/components/landing/components/carousel.jsx
  src/components/landing/components/events.jsx
  src/components/shared/container.jsx
  src/components/shared/footer.jsx
  src/components/shared/header.jsx
  src/components/shared/navbar.jsx
  src/components/shared/sidebar.jsx
Labels: enhancement

#21 20 create single event UI
  src/app/(home)/[eventId]/page.js
  src/components/single-event/components/singleEvent.jsx
  src/components/single-event/components/syaratKetentuan.jsx
  tailwind.config.js
Labels: enhancement

#23 feat: complete func landing
  src/components/landing/components/cardEvent.jsx
  src/components/landing/components/events.jsx
  src/components/landing/hooks/useDataLanding.jsx
Labels: enhancement

#25 24 create single event func
  package-lock.json
  package.json
  src/app/(home)/[eventId]/page.js
  src/app/layout.js
  src/components/single-event/components/singleEvent.jsx
  src/components/single-event/hooks/useJoinEvent.jsx
  src/components/single-event/hooks/useSingleData.jsx
Labels: enhancement

#28 bug: fix error handling join
  src/components/single-event/hooks/useJoinEvent.jsx
Labels: bug

#34 feat: complete func. search
  .env.local
  src/components/landing/components/events.jsx
  src/components/landing/hooks/useDataLanding.jsx
Labels: enhancement

#35 style(detail): improving ui detail event
  .env
  src/app/(home)/[eventid]/page.js
  src/components/landing/hooks/useDataLanding.jsx
  src/components/single-event/components/singleEvent.jsx
  src/components/single-event/components/termsConditions.jsx
  src/components/single-event/hooks/useSingleData.jsx
Labels: enhancement

#37 fix: add env to gitignore
  .env.local
  .gitignore
Labels: bug

#38 style(hero): change color button explore events
  src/app/(home)/[eventid]/page.js
  src/app/(home)/layout.js
  src/app/layout.js
  src/components/landing/components/hero.jsx
Labels: enhancement

#39 feat: add author event
  bun.lockb
  package.json
  src/components/single-event/components/singleEvent.jsx
  src/components/single-event/components/termsConditions.jsx
Labels: enhancement

#43 style: Login UI improvement
  src/components/auth/components/login.jsx
  src/components/auth/components/register.jsx
Labels: enhancement

#45 fix: description hero and grouping dateTime with button detail to center
  src/components/landing/components/cardEvent.jsx
  src/components/landing/components/hero.jsx
Labels: bug

#49 fix: mobile responsive for log in and register page
  src/components/auth/components/login.jsx
  src/components/auth/components/register.jsx
  src/components/landing/components/events.jsx
Labels: bug

#50 fix: size minimum for mobile responsive
  src/components/auth/components/login.jsx
  src/components/auth/components/register.jsx
Labels: bug

#52 style: improving ui dashboard and manage event
  src/app/dashboard/layout.js
  src/components/dashboard/components/dashboard.jsx
  src/components/manage-event/atoms/itemTable.jsx
  src/components/manage-event/components/eventForm.jsx
  src/components/manage-event/components/manageEvent.jsx
  src/components/shared/header.jsx
  src/components/shared/sidebar.jsx
Labels: enhancement

#53 update: delete input name and email
  src/components/single-event/components/singleEvent.jsx
Labels: enhancement

#54 bug: fix bug join event
  src/components/dashboard/components/dashboard.jsx
  src/components/dashboard/hooks/useRegisteredEvent.jsx
  src/components/single-event/components/singleEvent.jsx
  src/components/single-event/hooks/useJoinEvent.jsx
Labels: bug

#55 update: add link detail registered event
  src/app/(home)/[eventid]/page.js
  src/components/dashboard/components/card.jsx
  src/components/dashboard/components/dashboard.jsx
  src/components/dashboard/hooks/useRegisteredEvent.jsx
  src/components/manage-event/components/eventTable.jsx
  src/components/manage-event/components/manageEvent.jsx
  src/components/manage-event/hooks/useGetCreatedEvent.jsx
  src/components/single-event/hooks/useJoinEvent.jsx
  src/middleware.js
Labels: enhancement

#57 feat: add if user already join event and button confetti
  bun.lockb
  package.json
  src/components/landing/components/events.jsx
  src/components/manage-event/atoms/itemTable.jsx
  src/components/manage-event/components/eventForm.jsx
  src/components/manage-event/hooks/useCreateEvent.jsx
  src/components/manage-event/hooks/useDeleteEvent.jsx
  src/components/manage-event/hooks/useEditEvent.jsx
  src/components/manage-event/providers.jsx
  src/components/shared/navbar.jsx
  src/components/shared/sidebar.jsx
  src/components/single-event/components/singleEvent.jsx
Labels: enhancement

#59 feat: add author name in detail event
  package-lock.json
  src/components/single-event/components/singleEvent.jsx
  src/components/single-event/hooks/useAuthorEvent.jsx
Labels: enhancement

#60 update: move position author to grid join event
  src/components/single-event/components/singleEvent.jsx
  src/components/single-event/hooks/useAuthorEvent.jsx
  src/components/single-event/hooks/useJoinEvent.jsx
Labels: enhancement

#61 bug: solve bug route when login
  src/middleware.js
Labels: bug

#64 docs: update fitur and add other package
  README.md
Labels: documentation

#65 docs: add source link on other package
  README.md
Labels: documentation

#68 fix: guests can join the events
  src/components/auth/hooks/useRegister.jsx
  src/components/single-event/components/singleEvent.jsx
  src/components/single-event/hooks/useJoinEvent.jsx
Labels: enhancement

#69 docs: update fitur
  README.md
Labels: documentation
